var books=[
    {name:"Howl's Moving Castle"   ,
    id: 1   ,
    price:8.99 ,
    description:"This entrancing classic fantasy novel is filled with surprises at every turn. An international bestseller, ",
 category:"fantasy" ,  
imgs:["/media/howl1(1).jpg","/media/howl1(2).jpg"]    },

    {name: "Fellowship of the Ring"  ,
    id: 2   ,
    price:12.99 ,
    description:"One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them",
 category: "fantasy" ,  
imgs: ["/media/lotr1(1).jpg","/media/lotr1(2).jpg"]   },

    {name:"  the Sorcerer's Stone"   ,
    id:3    ,
    price:10 ,
    description:"Full of sympathetic characters, wildly imaginative situations, and countless exciting details",
 category:"fantasy" ,  
imgs: ["/media/hp1(1).jpg","/media/hp1(2).jpg"]   },

    {name: "The Hobbit"  ,
    id: 4   ,
    price:9 ,
    description:"the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon",
 category:"fantasy" ,  
imgs: ["/media/hob1(1).jpg","/media/hob1(2).jpg"]  },

    {name:"the Prisoner of Azkaban"   ,
    id: 5   ,
    price:11 ,
    description:"Harry Potter isn't safe, not even within the walls of his magical school      magical school               ",
 category:"fantasy" ,  
imgs: ["/media/hp3(1).jpg","/media/hp3(2).jpg"]   },

    {name:"the goblet of fire"   ,
    id: 6   ,
    price:11 ,
    description:"Harry Potter is midway through his training as a wizard and his coming of age.",
 category:"fantasy" ,  
imgs: ["/media/hp4(1).jpg","/media/hp4(2).jpg"]   },

    {name:"Chamber of Secrets"   ,
    id: 7   ,
    price:12 ,
    description:"Harry receives a warning from a strange impish creature",
 category:"fantasy" ,  
imgs: ["/media/hp2(1).jpg","/media/hp2(2).jpg"]   },

    {name:"Order of the Phoenix"   ,
    id: 8   ,
    price:13 ,
    description:"There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams",
 category:"fantasy" ,  
imgs: ["/media/hp5(1).jpg","/media/hp5(2).jpg"]   },

    {name:"the half-blood prince"   ,
    id: 9   ,
    price:13 ,
    description:"The war against Voldemort is not going well; even Muggle governments are noticing.",
 category:"fantasy" ,  
imgs: ["/media/hp6(1).jpg","/media/hp6(2).jpg"]   },

    {name:"the Deathly Hallows"   ,
    id: 10   ,
    price:13 ,
    description:"It's no longer safe for Harry at Hogwarts, so he and his best friends, Ron and Hermione, are on the run",
 category:"fantasy" ,  
imgs: ["/media/hp7(1).jpg","/media/hp7(2).jpg"]   },
    {name:"the two Towers"   ,
    id: 11  ,
    price:10 ,
    description:"One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them",
 category:"fantasy" ,  
imgs: ["/media/lotr2(1).jpg","/media/lotr2(2).jpg"]   },
    {name:"The Spook's Apprentice"   ,
    id: 12  ,
    price:16 ,
    description:"Thomas Ward is the seventh son of a seventh son and has been apprenticed to the local Spook.",
 category:"fantasy" ,  
imgs: ["/media/sa1(1).jpg","/media/sa1(2).jpg"]   },
    {name:"The Spook's curse"   ,
    id: 13  ,
    price:11 ,
    description:"The Spook and his apprentice, Thomas Ward have travelled to Priestown for some unfinished business",
 category:"fantasy" ,  
imgs: ["/media/sa2(1).jpg","/media/sa2(2).jpg"]   },
    {name:"The Spook's Secret"   ,
    id: 14  ,
    price:17 ,
    description:"the nights are drawing in and it's time for Tom and his master to move to Anglezarke",
 category:"fantasy" ,  
imgs: ["/media/sa3(1).jpg","/media/sa3(2).jpg"]   },
    {name:"the return of the king"   ,
    id: 15  ,
    price:15 ,
    description:"One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them",
 category:"fantasy" ,  
imgs: ["/media/lotr3(1).jfif","/media/lotr3(2).jfif"]   },
    {name:"Dracula"   ,
    id: 16  ,
    price:15 ,
    description:"The original world classic horror novel Dracula",
 category:"fantasy" ,  
imgs: ["/media/drac1(1).jfif","/media/drac1(2).jfif"]   },
    {name:"Ender's Game"   ,
    id: 17  ,
    price:13 ,
    description:"Andrew Ender Wiggin thinks he is playing computer simulated war games",
 category:"sci-fi" ,  
imgs: ["/media/ender1(1).jpg","/media/ender1(2).jpg"]   },
    {name:"speaker of the dead"   ,
    id: 18  ,
    price:19 ,
    description:"Andrew Ender Wiggin thinks he is playing computer simulated war games",
 category:"sci-fi" ,  
imgs: ["/media/ender2(1).jpg","/media/ender2(2).jpg"]   },
    {name:"Ender's shadow"   ,
    id: 19  ,
    price:11 ,
    description:"Andrew Ender Wiggin thinks he is playing computer simulated war games",
 category:"sci-fi" ,  
imgs: ["/media/ender3(1).jpg","/media/ender3(2).jpg"]   },
    {name:"Dune"   ,
    id: 20  ,
    price:11 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune1(1).jpg","/media/dune1(2).jpg"]   },
    {name:"	Dune Messiah"   ,
    id: 21  ,
    price:15 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune2(1).jpg","/media/dune2(2).jpg"]   },
    {name:"	Children of Dune "   ,
    id: 22  ,
    price:15 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune3(1).jpg","/media/dune3(2).jpg"]   },
    {name:"	God Emperor of Dune"   ,
    id: 23  ,
    price:21 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune4(1).jpg","/media/dune4(2).jpg"]   },
    {name:"Heretics of Dune"   ,
    id: 24  ,
    price:21 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune5(1).jpg","/media/dune5(2).jpg"]   },
    {name:"Chapterhouse: Dune"   ,
    id: 25  ,
    price:21 ,
    description:"Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides",
 category:"sci-fi" ,  
imgs: ["/media/dune6(1).jpg","/media/dune6(2).jpg"]   },
    {name:"Rendezvous with Rama"   ,
    id: 26  ,
    price:21 ,
    description:"only a few things are known about the celestial object that astronomers dub Rama",
 category:"sci-fi" ,  
imgs: ["/media/rama1(1).jpg","/media/rama1(2).jpg"]   },
    {name:"Rama II"   ,
    id: 27  ,
    price:21 ,
    description:"only a few things are known about the celestial object that astronomers dub Rama",
 category:"sci-fi" ,  
imgs: ["/media/rama2(1).jpg","/media/rama2(2).jpg"]   },
    {name:" The Garden of Rama "   ,
    id: 28  ,
    price:21 ,
    description:"only a few things are known about the celestial object that astronomers dub Rama",
 category:"sci-fi" ,  
imgs: ["/media/rama3(1).jpg","/media/rama3(2).jpg"]   },
    {name:" Sweetness at the Bottom of the Pie"   ,
    id: 29  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce1(1).jpg","/media/luce1(2).jpg"]   },
    {name:" Weed That Strings the Hangman's Bag"   ,
    id: 30  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce2(1).jpg","/media/luce2(2).jpg"]   },
    {name:" A Red Herring Without Mustard"   ,
    id: 31  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce3(1).jfif","/media/luce3(2).jfif"]   },
    {name:" I Am Half-Sick of Shadows"   ,
    id: 32  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce4(1).jpg","/media/luce4(2).jpg"]   },
    {name:" Speaking from Among the Bones"   ,
    id: 33  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce5(1).jpg","/media/luce5(2).jpg"]   },
    {name:" The Dead in Their Vaulted Arches"   ,
    id: 34  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce6(1).jfif","/media/luce6(2).jfif"]   },
    {name:" As Chimney Sweepers Come to Dust"   ,
    id: 35  ,
    price:21 ,
    description:" young Flavia de Luce, an aspiring chemist with a passion for poison, ",
 category:"mystery" ,  
imgs: ["/media/luce7(1).jfif","/media/luce7(2).jfif"]   },
    {name:"Murder on the Orient Express"   ,
    id: 36  ,
    price:21 ,
    description:"  detective Hercule Poirot must identify the murderer ",
 category:"mystery" ,  
imgs: ["/media/expres1(1).jpg","/media/expers1(2).jpg"]   },
    {name:"Peril at End House"   ,
    id: 37  ,
    price:21 ,
    description:"  detective Hercule Poirot must identify the murderer ",
 category:"mystery" ,  
imgs: ["/media/peril1(1).jpg","/media/peril1(2).jpg"]   },
    {name:"The Murder of Roger Ackroyd"   ,
    id: 38  ,
    price:21 ,
    description:"  detective Hercule Poirot must identify the murderer ",
 category:"mystery" ,  
imgs: ["/media/murder1(1).jfif","/media/murder1(2).jfif"]   },
    {name:"The Shining"   ,
    id: 39  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king1(1).jpg","/media/king1(2).jpg"]   },
    {name:"it"   ,
    id: 40  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king2(1).jpg","/media/king2(2).jpg"]   },
    {name:"Misery"   ,
    id: 41  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king3(1).jpg","/media/king3(2).jpg"]   },
    {name:"	Carrie"   ,
    id: 42  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king4(1).jpg","/media/king4(2).jpg"]   },
    {name:"The Gunslinger"   ,
    id: 43  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king5(1).jpg","/media/king5(2).jpg"]   },
    {name:"11/22/63"   ,
    id: 44  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king6(1).jpg","/media/king6(2).jpg"]   },
    {name:"The Green Mile"   ,
    id: 45  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king7(1).jpg","/media/king7(2).jpg"]   },
    {name:"Salem's Lot"   ,
    id: 46  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king8(1).jpg","/media/king8(2).jpg"]   },
    {name:"Pet Sematary"   ,
    id: 47  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king9(1).jpg","/media/king9(2).jpg"]   },
    {name:"the stand"   ,
    id: 48  ,
    price:21 ,
    description:" From legendary storyteller and #1 bestseller Stephen King ",
 category:"horor" ,  
imgs: ["/media/king10(1).jfif","/media/king10(2).jfif"]   },

  

]

